# Generated by Django 4.2.3 on 2023-07-15 15:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_profile_mobile_no_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bus_number',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Please enter a value in the format <3 letters>-###-###/####', regex='^[a-zA-Z]{3}-\\d{3}-\\d{3}/\\d{4}$')]),
        ),
    ]
