# Generated by Django 4.2.3 on 2023-07-15 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_profile_bus_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bus_number',
            new_name='adm_number',
        ),
    ]
