# Generated by Django 4.2.3 on 2023-07-15 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0004_rename_bus_number_profile_adm_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='adm_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Please enter a value in the format <3 letters>-###-###/####', regex='^[a-zA-Z]{3}-\\d{3}-\\d{3}/\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
