# Generated by Django 4.2.3 on 2023-07-15 19:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0005_alter_profile_adm_number_alter_profile_mobile_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='adm_number',
        ),
        migrations.AddField(
            model_name='profile',
            name='adm_no',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Please enter a value in the format <3 letters>-###-###/####', regex='^[a-zA-Z]{3}-\\d{3}-\\d{3}/\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
