# Generated by Django 4.2.3 on 2023-07-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0006_remove_profile_adm_number_profile_adm_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='adm_no',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
