# Generated by Django 4.2.3 on 2023-07-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0007_alter_profile_adm_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='adm_no',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
